[General]

# ==================================================
# WALLPAPER
# ==================================================

Background="Backgrounds/Mountain.jpg"

DimBackgroundImage="0.0"
ScaleImageCropped="true"

#ScreenWidth="1920"
#ScreenHeight="1080"

# ==================================================
# BLUR
# ==================================================

FullBlur="false"
PartialBlur="false"
BlurRadius="80"

# ==================================================
# LAYOUT
# ==================================================

HaveFormBackground="true"
FormPosition="left"

BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"

# ==================================================
# COLORS
# ==================================================

MainColor="white"
AccentColor="#89b4fa"
BackgroundColor=""

InterfaceShadowSize="6"
InterfaceShadowOpacity="0.5"

RoundCorners="20"
ScreenPadding="0"

# ==================================================
# FONT
# ==================================================

Font="JetBrainsMono Nerd Font"
FontSize=""

# ==================================================
# LOGIN BEHAVIOR
# ==================================================

ForceRightToLeft="false"

ForceLastUser="true"
ForcePasswordFocus="true"

ForceHideCompletePassword="false"

ForceHideVirtualKeyboardButton="true"

AllowEmptyPassword="false"
AllowBadUsernames="false"

# ==================================================
# POWER BUTTONS
# ==================================================

ForceHideSystemButtons="false"

# ==================================================
# CLOCK
# ==================================================

Locale=""

HourFormat="HH:mm"
DateFormat="dddd, d MMMM"

# ==================================================
# TEXT
# ==================================================

HeaderText=""

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword="Password"
TranslateShowPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateVirtualKeyboardButton=""
