exec-once = wayle panel start
# wallpaper
exec-once = nm-applet --indicator
exec-once = blueman-applet

exec-once = /usr/lib/polkit-kde-authentication-agent-1

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = hypridle

exec-once = [workspace 2 silent] zen-browser
exec-once = [workspace 3 silent] code