source = ~/.config/hypr/configs/variables.conf
source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/binds.conf

general {
    gaps_in = 2
    gaps_out = 3
    border_size = 0
}

decoration {
    rounding = 2

    blur {
        enabled = true
        size = 4
        passes = 2
    }
}