$wall = /home/adityapandey/Pictures/Wallpapers/076.png

# ==================================================
# GENERAL
# ==================================================

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
}

# ==================================================
# BACKGROUND
# ==================================================

background {
    monitor =
    path = $wall

    blur_passes = 0
    blur_size = 0

    contrast = 1.0
    brightness = 1.0
    vibrancy = 0.0
}

# ==================================================
# LEFT BLUR PANEL
# ==================================================

shape {
    monitor =

    size = 520, 1080

    color = rgba(15,15,20,0.25)

    rounding = 0

    border_size = 0

    position = 0, 0

    halign = left
    valign = center
}

# ==================================================
# TIME
# ==================================================

label {
    monitor =

    text = cmd[update:1000] date +"%H:%M"

    color = rgba(220,220,220,0.85)

    font_size = 42
    font_family = JetBrainsMono Nerd Font

    position = 115, 190

    halign = left
    valign = center
}

# ==================================================
# DATE
# ==================================================

label {
    monitor =

    text = cmd[update:60000] date +"%A, %B %d"

    color = rgba(220,220,220,0.75)

    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 115, 125

    halign = left
    valign = center
}

# ==================================================
# USER BOX
# ==================================================

shape {
    monitor =

    size = 340, 54

    color = rgba(255,255,255,0.15)

    rounding = 27

    border_size = 0

    position = 110, -120

    halign = left
    valign = center
}

label {
    monitor =

    text =  $USER

    color = rgba(235,235,235,0.90)

    font_size = 16
    font_family = JetBrainsMono Nerd Font

    position = 190, -120

    halign = left
    valign = center
}

# ==================================================
# PASSWORD FIELD
# ==================================================

input-field {
    monitor =

    size = 340, 54

    outline_thickness = 0

    outer_color = rgba(0,0,0,0)

    inner_color = rgba(255,255,255,0.10)

    font_color = rgb(235,235,235)

    fade_on_empty = false

    font_family = JetBrainsMono Nerd Font

    hide_input = false

    placeholder_text = <span foreground="##ffffff99">🔒 Password</span>

    rounding = 27

    dots_center = true
    dots_size = 0.35
    dots_spacing = 0.35

    position = 110, -195

    halign = left
    valign = center
}