source = ~/.config/hypr/configs/variables.conf
source = ~/.config/hypr/configs/startup.conf
source = ~/.config/hypr/configs/binds.conf

monitor = eDP-1,1920x1080@144,0x0,1.25

general {
    gaps_in = 2
    gaps_out = 3
    border_size = 0
}

decoration {
    rounding = 2

    blur {
        enabled = true
        size = 4
        passes = 2
    }
}

input {
    numlock_by_default = true
}

windowrule {
    name = my-ghostty-rule
    match:class = ^(com\.mitchellh\.ghostty\.float)$
    float = on
    center = on
    size = 1200 700
}

layerrule {
    name = rofi-blur
    match:namespace = rofi
    blur = on
}

animations {
    enabled = true

    bezier = bounce, 0.5, 1.5, 0.5, 1

    animation = windows, 1, 5, bounce, popin 50%
    animation = windowsOut, 1, 4, default, popin 80%
    animation = fade, 1, 4, default
    animation = workspaces, 1, 5, bounce, slide
}

dwindle {
    preserve_split = true
}


